export default [
  {
    author: 'Leo Tolstoy',
    country: 'Russia',
    language: 'Russian',
    pages: 864,
    title: 'War and Peace',
    year: 1869,
  },
  {
    author: 'Jane Austen',
    country: 'United Kingdom',
    language: 'English',
    pages: 432,
    title: 'Pride and Prejudice',
    year: 1813,
  },
  {
    author: 'Fyodor Dostoevsky',
    country: 'Russia',
    language: 'Russian',
    pages: 551,
    title: 'Crime and Punishment',
    year: 1866,
  },
  {
    author: 'George Orwell',
    country: 'United Kingdom',
    language: 'English',
    pages: 328,
    title: '1984',
    year: 1949,
  },
  {
    author: 'Mark Twain',
    country: 'United States',
    language: 'English',
    pages: 224,
    title: 'The Adventures of Huckleberry Finn',
    year: 1884,
  },
  {
    author: 'Gabriel García Márquez',
    country: 'Colombia',
    language: 'Spanish',
    pages: 417,
    title: 'One Hundred Years of Solitude',
    year: 1967,
  },
  {
    author: 'Harper Lee',
    country: 'United States',
    language: 'English',
    pages: 324,
    title: 'To Kill a Mockingbird',
    year: 1960,
  },
  {
    author: 'Hermann Hesse',
    country: 'Germany',
    language: 'German',
    pages: 177,
    title: 'Siddhartha',
    year: 1922,
  },
  {
    author: 'J.K. Rowling',
    country: 'United Kingdom',
    language: 'English',
    pages: 309,
    title: "Harry Potter and the Philosopher's Stone",
    year: 1997,
  },
  {
    author: 'Toni Morrison',
    country: 'United States',
    language: 'English',
    pages: 321,
    title: 'Beloved',
    year: 1987,
  },
  {
    author: 'Jane Austen',
    country: 'United Kingdom',
    language: 'English',
    pages: 368,
    title: 'Sense and Sensibility',
    year: 1811,
  },
  {
    author: 'Fyodor Dostoevsky',
    country: 'Russia',
    language: 'Russian',
    pages: 430,
    title: 'The Brothers Karamazov',
    year: 1880,
  },
  {
    author: 'George Orwell',
    country: 'United Kingdom',
    language: 'English',
    pages: 276,
    title: 'Animal Farm',
    year: 1945,
  },
  {
    author: 'Mark Twain',
    country: 'United States',
    language: 'English',
    pages: 366,
    title: 'The Adventures of Tom Sawyer',
    year: 1876,
  },
  {
    author: 'Gabriel García Márquez',
    country: 'Colombia',
    language: 'Spanish',
    pages: 352,
    title: 'Love in the Time of Cholera',
    year: 1985,
  },
  {
    author: 'Harper Lee',
    country: 'United States',
    language: 'English',
    pages: 273,
    title: 'Go Set a Watchman',
    year: 2015,
  },
  {
    author: 'Hermann Hesse',
    country: 'Germany',
    language: 'German',
    pages: 320,
    title: 'Steppenwolf',
    year: 1927,
  },
  {
    author: 'J.K. Rowling',
    country: 'United Kingdom',
    language: 'English',
    pages: 435,
    title: 'Harry Potter and the Chamber of Secrets',
    year: 1998,
  },
  {
    author: 'Toni Morrison',
    country: 'United States',
    language: 'English',
    pages: 276,
    title: 'Song of Solomon',
    year: 1977,
  },
  {
    author: 'George Orwell',
    country: 'United Kingdom',
    language: 'English',
    pages: 328,
    title: 'Nineteen Eighty-Four',
    year: 1949,
  },
  {
    author: 'J.R.R. Tolkien',
    country: 'United Kingdom',
    language: 'English',
    pages: 423,
    title: 'The Lord of the Rings',
    year: 1954,
  },
  {
    author: 'Leo Tolstoy',
    country: 'Russia',
    language: 'Russian',
    pages: 864,
    title: 'War and Peace',
    year: 1869,
  },
  {
    author: 'F. Scott Fitzgerald',
    country: 'United States',
    language: 'English',
    pages: 180,
    title: 'The Great Gatsby',
    year: 1925,
  },
  {
    author: 'Harper Lee',
    country: 'United States',
    language: 'English',
    pages: 336,
    title: 'To Kill a Mockingbird',
    year: 1960,
  },
  {
    author: 'Mark Twain',
    country: 'United States',
    language: 'English',
    pages: 224,
    title: 'Adventures of Huckleberry Finn',
    year: 1884,
  },
  {
    author: 'Gabriel García Márquez',
    country: 'Colombia',
    language: 'Spanish',
    pages: 417,
    title: 'One Hundred Years of Solitude',
    year: 1967,
  },
  {
    author: 'Jane Austen',
    country: 'United Kingdom',
    language: 'English',
    pages: 279,
    title: 'Pride and Prejudice',
    year: 1813,
  },
  {
    author: 'Miguel de Cervantes',
    country: 'Spain',
    language: 'Spanish',
    pages: 863,
    title: 'Don Quixote',
    year: 1605,
  },
  {
    author: 'Arthur Conan Doyle',
    country: 'United Kingdom',
    language: 'English',
    pages: 240,
    title: 'The Adventures of Sherlock Holmes',
    year: 1892,
  },
  {
    author: 'Hermann Hesse',
    country: 'Germany',
    language: 'German',
    pages: 128,
    title: 'Siddhartha',
    year: 1922,
  },
  {
    author: 'Charles Dickens',
    country: 'United Kingdom',
    language: 'English',
    pages: 544,
    title: 'A Tale of Two Cities',
    year: 1859,
  },
  {
    author: 'Victor Hugo',
    country: 'France',
    language: 'French',
    pages: 1232,
    title: 'Les Misérables',
    year: 1862,
  },
  {
    author: 'Homer',
    country: 'Greece',
    language: 'Greek',
    pages: 608,
    title: 'The Odyssey',
    year: -800,
  },
  {
    author: 'Fyodor Dostoevsky',
    country: 'Russia',
    language: 'Russian',
    pages: 551,
    title: 'Crime and Punishment',
    year: 1866,
  },
  {
    author: 'Gustave Flaubert',
    country: 'France',
    language: 'French',
    pages: 528,
    title: 'Madame Bovary',
    year: 1856,
  },
  {
    author: 'Oscar Wilde',
    country: 'Ireland',
    language: 'English',
    pages: 76,
    title: 'The Picture of Dorian Gray',
    year: 1890,
  },
  {
    author: 'J.D. Salinger',
    country: 'United States',
    language: 'English',
    pages: 277,
    title: 'The Catcher in the Rye',
    year: 1951,
  },
  {
    author: 'Emily Brontë',
    country: 'United Kingdom',
    language: 'English',
    pages: 342,
    title: 'Wuthering Heights',
    year: 1847,
  },
  {
    author: 'H.G. Wells',
    country: 'United Kingdom',
    language: 'English',
    pages: 207,
    title: 'The Time Machine',
    year: 1895,
  },
  {
    author: 'Antoine de Saint-Exupéry',
    country: 'France',
    language: 'French',
    pages: 96,
    title: 'The Little Prince',
    year: 1943,
  },
  {
    author: 'Lewis Carroll',
    country: 'United Kingdom',
    language: 'English',
    pages: 239,
    title: "Alice's Adventures in Wonderland",
    year: 1865,
  },
  {
    author: 'Charlotte Brontë',
    country: 'United Kingdom',
    language: 'English',
    pages: 489,
    title: 'Jane Eyre',
    year: 1847,
  },
  {
    author: 'Jules Verne',
    country: 'France',
    language: 'French',
    pages: 219,
    title: 'Twenty Thousand Leagues Under the Sea',
    year: 1870,
  },
  {
    author: 'Mary Shelley',
    country: 'United Kingdom',
    language: 'English',
    pages: 280,
    title: 'Frankenstein',
    year: 1818,
  },
];
