export default [
  {
    author: 'Leo Tolstoy',
    country: 'Russia',
    language: 'Russian',
    pages: 864,
    title: 'War and Peace',
    year: 1869,
  },
  {
    author: 'Jane Austen',
    country: 'United Kingdom',
    language: 'English',
    pages: 432,
    title: 'Pride and Prejudice',
    year: 1813,
  },
  {
    author: 'Fyodor Dostoevsky',
    country: 'Russia',
    language: 'Russian',
    pages: 551,
    title: 'Crime and Punishment',
    year: 1866,
  },
  {
    author: 'George Orwell',
    country: 'United Kingdom',
    language: 'English',
    pages: 328,
    title: '1984',
    year: 1949,
  },
  {
    author: 'Mark Twain',
    country: 'United States',
    language: 'English',
    pages: 224,
    title: 'The Adventures of Huckleberry Finn',
    year: 1884,
  },
  {
    author: 'Gabriel García Márquez',
    country: 'Colombia',
    language: 'Spanish',
    pages: 417,
    title: 'One Hundred Years of Solitude',
    year: 1967,
  },
  {
    author: 'Harper Lee',
    country: 'United States',
    language: 'English',
    pages: 324,
    title: 'To Kill a Mockingbird',
    year: 1960,
  },
  {
    author: 'Hermann Hesse',
    country: 'Germany',
    language: 'German',
    pages: 177,
    title: 'Siddhartha',
    year: 1922,
  },
  {
    author: 'J.K. Rowling',
    country: 'United Kingdom',
    language: 'English',
    pages: 309,
    title: "Harry Potter and the Philosopher's Stone",
    year: 1997,
  },
  {
    author: 'Toni Morrison',
    country: 'United States',
    language: 'English',
    pages: 321,
    title: 'Beloved',
    year: 1987,
  },
  {
    author: 'Jane Austen',
    country: 'United Kingdom',
    language: 'English',
    pages: 368,
    title: 'Sense and Sensibility',
    year: 1811,
  },
  {
    author: 'Fyodor Dostoevsky',
    country: 'Russia',
    language: 'Russian',
    pages: 430,
    title: 'The Brothers Karamazov',
    year: 1880,
  },
  {
    author: 'George Orwell',
    country: 'United Kingdom',
    language: 'English',
    pages: 276,
    title: 'Animal Farm',
    year: 1945,
  },
  {
    author: 'Mark Twain',
    country: 'United States',
    language: 'English',
    pages: 366,
    title: 'The Adventures of Tom Sawyer',
    year: 1876,
  },
  {
    author: 'Gabriel García Márquez',
    country: 'Colombia',
    language: 'Spanish',
    pages: 352,
    title: 'Love in the Time of Cholera',
    year: 1985,
  },
  {
    author: 'Harper Lee',
    country: 'United States',
    language: 'English',
    pages: 273,
    title: 'Go Set a Watchman',
    year: 2015,
  },
  {
    author: 'Hermann Hesse',
    country: 'Germany',
    language: 'German',
    pages: 320,
    title: 'Steppenwolf',
    year: 1927,
  },
  {
    author: 'J.K. Rowling',
    country: 'United Kingdom',
    language: 'English',
    pages: 435,
    title: 'Harry Potter and the Chamber of Secrets',
    year: 1998,
  },
  {
    author: 'Toni Morrison',
    country: 'United States',
    language: 'English',
    pages: 276,
    title: 'Song of Solomon',
    year: 1977,
  },
];
